version: 0.2


phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing npm...
      - npm install -g @angular/cli
      - npm i
  pre_build:
    commands:
      - echo Building Angular project
      - pwd
      - mkdir -p src/app/assets/config
      - printf '{"url":"%s","token":"%s"}' $APM_SERVER_URL $APM_SECRET_TOKEN > src/app/assets/config/apm-config.json
      - cat src/app/assets/config/apm-config.json
      - ng build --configuration=perf --aot
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - BUILD_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $SERVICE_NAME:$BUILD_ID .
      - docker tag $SERVICE_NAME:$BUILD_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$BUILD_ID > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - Dockerfile
    - dist/caliber-ui/

